version: "3"
services:
  #  controller:
  #    build: ./
  #    #:/opt/project/ryu/app#
  #    #    image: andi95/bobi_controller
  #    #    command: tail -F anything
  #    command: /bin/sh -c "cd app/ && python3 simple_monitor_13.py"
  #    cap_add:
  #      - NET_ADMIN
  #    networks:
  #      ctrl_net:
  #        ipv4_address: 192.168.1.60
  #
  #  controller2:
  #    build: ./
  #    #:/opt/project/ryu/app#
  #    #    image: andi95/bobi_controller
  #    #    command: tail -F anything
  #    command: /bin/sh -c "cd app/ && python3 simple_monitor_13.py"
  #    cap_add:
  #      - NET_ADMIN
  #    networks:
  #      ctrl_net:
  #        ipv4_address: 192.168.1.69


  #  pkt_generator:
  #    #    image: pkt_generator
  #    build: pkt_generator/
  #    #    command: tail -F anything
  #    command: python3 TCP_OFPTxx.py 192.168.1.60
  #    cap_add:
  #      - NET_ADMIN
  #    depends_on:
  #      - controller
  #    networks:
  #      ctrl_net:
  #        ipv4_address: 192.168.1.79


  switch:
    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
    image: switch_develop
#    build: ./switch_develop
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: /bin/sh /bin/boot.sh
    networks:
      ctrl_net:
        ipv4_address: 192.168.1.2
      ctrl_net2:
        ipv4_address: 192.168.2.2

  switch2:
    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
    #    image: socketplane/openvswitch
    image: switch_develop
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    #    command: python3 TCP_OFPTxx.py 192.168.1.2
    #    command: tail -F anything
    command: /bin/sh /bin/boot.sh && tail -F anything
    networks:
      ctrl_net:
        ipv4_address: 192.168.1.3
      ctrl_net3:
        ipv4_address: 192.168.3.3

  switch3:
    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
    #    image: socketplane/openvswitch
    image: switch_develop
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    #    command: python3 TCP_OFPTxx.py 192.168.1.2
    #    command: tail -F anything
    command: /bin/sh /bin/boot.sh && tail -F anything
    networks:
      ctrl_net2:
        ipv4_address: 192.168.2.4
      ctrl_net3:
        ipv4_address: 192.168.3.4


#  watch "ovs-vsctl list controller"
#  watch "ovs-ofctl -O OpenFlow13 dump-flows br0"

networks:
  ctrl_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
  ctrl_net2:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
  ctrl_net3:
    ipam:
      driver: default
      config:
        - subnet: "192.168.3.0/24"


