version: "3"
services:
  #  controller:
  #    build: ./
  #    #:/opt/project/ryu/app#
  #    #    image: andi95/bobi_controller
  #    #    command: tail -F anything
  #    command: /bin/sh -c "cd app/ && python3 simple_monitor_13.py"
  #    cap_add:
  #      - NET_ADMIN
  #    networks:
  #      ctrl_net:
  #        ipv4_address: 192.168.1.60
  #
#  controller2:
#    image: controller
#    command: tail -F anything
#    #    command: /bin/sh -c "cd app/ && python3 simple_monitor_13.py"
#    cap_add:
#      - NET_ADMIN
#    networks:
#      ctrl_net:
#        ipv4_address: 192.168.1.69
#
#
  pkt_generator:
    #    image: pkt_generator
    build: pkt_generator/
    command: tail -F anything
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      ctrl_net2:
        ipv4_address: 192.168.2.99


  switch:
    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
    image: switch_develop
    #    build: ./switch_develop
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: /bin/sh /bin/boot.sh
    tty: true
    networks:
      ctrl_net:
        ipv4_address: 192.168.0.79
#      ctrl_net2:
#        ipv4_address: 192.168.2.59


  switch2:
    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
    #    image: socketplane/openvswitch
    image: switch_develop
    links:
      - switch
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: /bin/sh /bin/boot.sh
    tty: true
    networks:
      ctrl_net:
        ipv4_address: 192.168.0.59
      ctrl_net2:
        ipv4_address: 192.168.2.69

  switch3:
      #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
      #    image: socketplane/openvswitch
      image: switch_develop
      links:
        - switch
      cap_add:
        - NET_ADMIN
        - SYS_ADMIN
      command: /bin/sh /bin/boot.sh
      tty: true
      networks:
        ctrl_net:
          ipv4_address: 192.168.0.89
        ctrl_net2:
          ipv4_address: 192.168.2.89

#  switch3:
#    #    build: /home/ubuntu/PycharmProjects/Testi_Mininet/switch_develop/Dockerfile
#    #    image: socketplane/openvswitch
#    image: switch_develop
#    cap_add:
#      - NET_ADMIN
#      - SYS_ADMIN
#    #    command: python3 TCP_OFPTxx.py 192.168.1.2
##    command: tail -F anything
#    command: /bin/sh /bin/boot.sh
#    tty: true


#  watch "ovs-vsctl list controller"
#  watch "ovs-ofctl -O OpenFlow13 dump-flows br0"

networks:
  ctrl_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
  ctrl_net2:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
#  ctrl_net3:
#    ipam:
#      driver: default
#      config:
#        - subnet: "192.168.1.0/24"


